import pycountry

country_list = [country.name for country in pycountry.countries]
font = 'Arial'
timezones = [
    '',
    'America/New_York',
    'America/Los_Angeles',
    'America/Chicago',
    'America/Denver',
    'America/Toronto',
    'Europe/London',
    'Europe/Paris',
    'Europe/Berlin',
    'Asia/Tokyo',
    'Asia/Shanghai',
    'Asia/Dubai',
    'Australia/Sydney',
    'Africa/Johannesburg',
    'Pacific/Honolulu',
    'Pacific/Auckland',
    'Indian/Mumbai'
]
button_font_size = 10
table_list = ["Flights", "Pilots", "Aircrafts", "Destinations"]
table_list.sort()

junction_list = ["Pilot_Flight_JUNC"]
gender_list = ['',"Male", "Female", "Transgender", "Non-Binary"]
seniorities = [
    '','Cadet', 'Training Pilot', 'Second Officer', 'First Officer', 'Co-Pilot',
    'Senior First Officer', 'Captain'
]
international_airport_codes = [
  'ATL', 'LAX', 'ORD', 'DFW', 'JFK', 'DEN', 'SFO', 'SEA', 'LAS', 'MCO',
  'EWR', 'MIA', 'CLT', 'PHX', 'IAH', 'MSP', 'DTW', 'BOS', 'PHL', 'LGA',
  'FLL', 'BWI', 'SLC', 'SAN', 'IAD', 'DCA', 'MDW', 'MCI', 'MKE', 'HNL',
  'BNA', 'SMF', 'OAK', 'PDX', 'MSY', 'RDU', 'SJC', 'RSW', 'SNA', 'SAT',
  'PIT', 'TPA', 'IND', 'CLE', 'CMH', 'AUS', 'BUR', 'OGG', 'LGB', 'PBI',
  'SDF', 'BDL', 'JAX', 'BUF', 'OMA', 'ANC', 'LIT', 'TUL', 'OKC', 'BHM',
  'CRP', 'PNS', 'MEM', 'GRR', 'RNO', 'ROC', 'CAK', 'SYR', 'CHS', 'SAV',
  'ELP', 'TUS', 'ABQ', 'ICT', 'DAY', 'BOI', 'MSO', 'GEG', 'MHT', 'FAT',
  'GSO', 'ORF', 'HSV', 'JAN', 'FAR', 'BTV', 'GPT', 'LEX', 'LNK', 'MRY',
  'PSP', 'AGS', 'MOB', 'FSD', 'SWF', 'SGF', 'TYS', 'GSO', 'RIC', 'BGR',
  'DSM', 'ALB', 'SBN', 'AVL', 'FLG', 'ICT', 'PWM', 'BMI', 'ABE', 'CID',
  'SPI', 'RST', 'SHV', 'MLI', 'DAB', 'GJT', 'COS', 'GSO', 'CHS', 
  'MGM', 'CHA', 'PIA', 'GPT', 'MOT', 'BFL', 'SGF', 'TRI', 'CAE',
  'FSD', 'GRR', 'RNO', 'ORH', 'SYR', 'MHT', 'RFD', 'CHO', 'CID', 'BGM',
  'SBA', 'LYH', 'TWF', 'FCA', 'FLG', 'GSO', 'HRL', 'AVL', 'ACT', 'SBP',
  'BRO', 'STX', 'ILM', 'TXK', 'SWO', 'ELM', 'JNU', 'MBS', 'PIH', 'DRO',
  'EWN', 'PSC', 'RKS', 'AGS', 'EUG', 'GFK', 'DIK', 'PBG', 'BPT', 'GGG',
  'GUM', 'PSG', 'SCC', 'KTN', 'SGU', 'WRG', 'OME', 'YAK', 'CDV', 'GRR',
  'LWB', 'KTN', 'EWN', 'GJT', 'OTH', 'ACV', 'RFD', 'MEI',
  'ABI', 'FSM', 'TWF', 'ILM', 'ELM', 'LBE', 'SBA', 'DIK', 'EUG', 'TOL',
  'ERI', 'BTM', 'CHO', 'AEX', 'STX', 'YUM', 'BPT', 'GGG', 'GGG', 'BFL',
  'HVN', 'MFE', 'SUN', 'RDM', 'SAF', 'BRO', 'TLH', 'TYR', 'BRO',
  'SCE', 'SPI', 'AEX', 'MEI', 'TUP', 'TXK',
  'PIH',
]
international_airport_codes.sort()
flight_type_list = [
  "",
    'Commercial', 'Passenger', 'Cargo', 'Government', 'Special Purpose',
    'Medical', 'General'
]
aircraft_ownership_types = [
    "",
    "Private Ownership",
    "Corporate Ownership",
    "Government Ownership",
    "Fractional Ownership",
    "Charter Ownership",
    "Lease Ownership",
    "Cooperative Ownership",
    "Aircraft Partnership",
    "Aircraft Syndicate",
    "Timeshare Ownership",
    "Club Ownership",
    "Rental Ownership",
    "Government Leased Ownership",
    "Non-Profit or NGO Ownership",
    "Military Ownership",
    "Municipal or Local Government Ownership",
]
aircraft_ownership_types.sort()
aircraft_engine_types = [
    "",
    "Turboprop Engines",
    "Turbofan Engines",
    "Turbojet Engines",
    "Turboshaft Engines",
    "Ramjet Engines",
    "Scramjet Engines",
    "Rocket Engines",
    "Electric Propulsion (Electric Motors)",
    "Piston Engines",
    "Hybrid Engines",
]
manufacturer_list = [
    "","Airbus", "Boeing", "Lockheed Martin", "Embraer", "Bombardier",
    "Dassault Aviation", "Northrop Grumman", "Sukhoi", "Mikoyan", "Saab",
    "Eurofighter GmbH", "BAE Systems", "Bell Textron", "Sikorsky Aircraft",
    "Gulfstream Aerospace", "Cessna", "Piper Aircraft", "Beechcraft",
    "Antonov", "Tupolev"
]
manufacturer_list.sort()
models_list = [
    "","Air Force One (Boeing VC-25)", "Marine One (Sikorsky VH-3D Sea King)",
    "Presidential State Car (Cadillac One)", "Bell UH-1 Iroquois (Huey)",
    "Lockheed C-130 Hercules", "Lockheed C-5 Galaxy", "Boeing E-4B Nightwatch",
    "Boeing E-3 Sentry (AWACS)", "Lockheed P-3 Orion",
    "Lockheed C-130J Super Hercules", "Beechcraft King Air",
    "Eurocopter AS365 Dauphin", "Sikorsky UH-60 Black Hawk",
    "AgustaWestland AW139", "Gulfstream G550", "Bombardier Global Express",
    "Dassault Falcon 7X", "Boeing P-8 Poseidon",
    "Embraer EMB 314 Super Tucano", "Lockheed F-16 Fighting Falcon",
    "Boeing F-15 Eagle", "Lockheed Martin F-22 Raptor",
    "Northrop Grumman B-2 Spirit", "Lockheed Martin F-35 Lightning II",
    "Boeing AH-64 Apache", "Boeing F/A-18 Hornet", "Mikoyan MiG-29",
    "Sukhoi Su-27", "Dassault Rafale", "Eurofighter Typhoon",
    "Saab JAS 39 Gripen", "North American F-86 Sabre", "Sukhoi Su-35",
    "Tupolev Tu-95 Bear", "Lockheed C-130 Hercules",
    "Boeing C-17 Globemaster III", "Antonov An-124 Ruslan",
    "Grumman E-2 Hawkeye", "Boeing KC-135 Stratotanker", "Airbus A220",
    "Airbus A318", "Airbus A319", "Airbus A320", "Airbus A321", "Airbus A330",
    "Airbus A340", "Airbus A350", "Airbus A380", "Boeing 717", "Boeing 727",
    "Boeing 737", "Boeing 747", "Boeing 757", "Boeing 767", "Boeing 777",
    "Boeing 787", "Embraer E-Jet Series", "Bombardier CRJ Series",
    "Bombardier Dash 8", "McDonnell Douglas MD-80", "McDonnell Douglas MD-90",
    "McDonnell Douglas MD-11"
]
models_list.sort()
insured = ['',"Insured by airline", "Insured by Seller", "Not Insured"]
nationalities = [
    '',
    "Afghan",
    "Albanian",
    "Algerian",
    "American",
    "Andorran",
    "Angolan",
    "Antiguan",
    "Argentinian",
    "Armenian",
    "Australian",
    "Austrian",
    "Azerbaijani",
    "Bahamian",
    "Bahraini",
    "Bangladeshi",
    "Barbadian",
    "Belarusian",
    "Belgian",
    "Belizean",
    "Beninese",
    "Bhutanese",
    "Bolivian",
    "Bosnian",
    "Botswanan",
    "Brazilian",
    "British",
    "Bruneian",
    "Bulgarian",
    "Burkinabe",
    "Burmese",
    "Burundian",
    "Cambodian",
    "Cameroonian",
    "Canadian",
    "Cape Verdean",
    "Central African",
    "Chadian",
    "Chilean",
    "Chinese",
    "Colombian",
    "Comoran",
    "Congolese",
    "Costa Rican",
    "Croatian",
    "Cuban",
    "Cypriot",
    "Czech",
    "Danish",
    "Djibouti",
    "Dominican",
    "Dutch",
    "East Timorese",
    "Ecuadorean",
    "Egyptian",
    "Salvadoran",
    "Equatorial Guinean",
    "Eritrean",
    "Estonian",
    "Ethiopian",
    "Fijian",
    "Finnish",
    "French",
    "Gabonese",
    "Gambian",
    "Georgian",
    "German",
    "Ghanaian",
    "Greek",
    "Grenadian",
    "Guatemalan",
    "Guinea-Bissauan",
    "Guinean",
    "Guyanese",
    "Haitian",
    "Herzegovinian",
    "Honduran",
    "Hungarian",
    "I-Kiribati",
    "Icelander",
    "Indian",
    "Indonesian",
    "Iranian",
    "Iraqi",
    "Irish",
    "Israeli",
    "Italian",
    "Ivorian",
    "Jamaican",
    "Japanese",
    "Jordanian",
    "Kazakhstani",
    "Kenyan",
    "Kittian and Nevisian",
    "Kuwaiti",
    "Kyrgyz",
    "Laotian",
    "Latvian",
    "Lebanese",
    "Liberian",
    "Libyan",
    "Liechtensteiner",
    "Lithuanian",
    "Luxembourger",
    "Macedonian",
    "Malagasy",
    "Malawian",
    "Malaysian",
    "Maldivan",
    "Malian",
    "Maltese",
    "Marshallese",
    "Mauritanian",
    "Mauritian",
    "Mexican",
    "Micronesian",
    "Moldovan",
    "Monacan",
    "Mongolian",
    "Moroccan",
    "Mosotho",
    "Motswana",
    "Mozambican",
    "Namibian",
    "Nauruan",
    "Nepalese",
    "New Zealander",
    "Nicaraguan",
    "Nigerian",
    "Nigerien",
    "North Korean",
    "Northern Irish",
    "Norwegian",
    "Omani",
    "Pakistani",
    "Palauan",
    "Panamanian",
    "Papua New Guinean",
    "Paraguayan",
    "Peruvian",
    "Polish",
    "Portuguese",
    "Qatari",
    "Romanian",
    "Russian",
    "Rwandan",
    "Saint Lucian",
    "Salvadoran",
    "Samoan",
    "San Marinese",
    "Sao Tomean",
    "Saudi",
    "Scottish",
    "Senegalese",
    "Serbian",
    "Seychellois",
    "Sierra Leonean",
    "Singaporean",
    "Slovakian",
    "Slovenian",
    "Solomon Islander",
    "Somali",
    "South African",
    "South Korean",
    "South Sudanese",
    "Spanish",
    "Sri Lankan",
    "Sudanese",
    "Surinamer",
    "Swazi",
    "Swedish",
    "Swiss",
    "Syrian",
    "Taiwanese",
    "Tajik",
    "Tanzanian",
    "Thai",
    "Togolese",
    "Tongan",
    "Trinidadian/Tobagonian",
    "Tunisian",
    "Turkish",
    "Tuvaluan",
    "Ugandan",
    "Ukrainian",
    "United Arab Emirates",
    "British",
    "Uruguayan",
    "Uzbekistani",
    "Vanuatuan",
    "Venezuelan",
    "Vietnamese",
    "Welsh",
    "Yemenite",
    "Zambian",
    "Zimbabwean",
]
